### ISSUE TITLE
Question : How to contact you ?

### ISSUE THREAD

**Issue by thomakl** [b04rdr1d3r/M2KC-Streamdeck-profile-for-DCS-Interface#1]
Hi @b04rdr1d3r,

I am very interested in your current projects on the M2KC in DCS.
Is there a way I can contact you for further discussion, please ?

Thank you for your time,
Best,

Tomek

**Comment by b04rdr1d3r** [comment]
Hi there ! I dropped you an email with contact details.

Thanks.

Regards
