### ISSUE TITLE
Empty Profile

### ISSUE THREAD

**Issue by ghost** [b04rdr1d3r/M2KC-Streamdeck-profile-for-DCS-Interface#2]
Hi,

i downloadend your Profile. And with Version 1.13 i only get an empty Profile in Stream Deck with the Name M-2000C copy (i don't have a second profile with this name in my list). Same Proboem with the Standard and the XL file

See attached Screenshot.

1.12 works fine.

Greetings
![Screenshot 2022-12-27 111858](https://user-images.githubusercontent.com/49154963/209651976-49f06d8f-c354-41e0-b35f-0b545f9af190.jpg)

**Comment by b04rdr1d3r** [comment]
Thanks for reaching out.

Apparently this is linked to an issue with the streamdeck software itself.
I suggest you upgrade within the streamdeck App to the latest version (6.x
I believe). From what we have observed, it seems to solve the issue...

Let me know if this fixed it!

**Comment by ghost** [comment]
HI Sorry for the late Answer.

Yeah that solved the problem. Thanks.

Great Work.

One last thing, if you would add the github link to the File on dcsworld. It would be easier to find the repo :-)
