### ISSUE TITLE
VAL Button on PCN

### ISSUE THREAD

**Issue by ghost** [b04rdr1d3r/M2KC-Streamdeck-profile-for-DCS-Interface#3]
Hi,

i have the Problem, that the VAL Button on the PCN is illuminated all time. Also the value for DCS-ID is 581. (REC, BAD, MAR working fine)

I tried to find a different / correct DCS-ID. But i wasn't able to find some.
Unfortunaly i think it is poblem in the Module. Or did i miss something?

I also checked DCS-BIOS, the value there is also 1 the whole time.

Maybe you have some solutions.

I also noticed that some Buttons (Missle Prep) and TOT/PAR switch are not working.
- Missle Prep (currently only placeholders, if iam right)
- TOT/PAR (it seems Keybind is not set per standard)

If you are interessted, and If (big if) iam able to find some solutions to the above problems, i will create a pull request.

**Comment by b04rdr1d3r** [comment]
thanks a lot for your report. feel free to hop on our discord to interact easier with us ==> https://discord.gg/9FtGbP846A

I fixed the PCN issue and also made the TOT/PAR button functional natively (it did require a keyboard shortcut to work)

head to v1.14 for the fixed version !
